### ISSUE TITLE
Current version is not installable

### ISSUE THREAD

**Issue by ju1ius** [souporserious/react-view-pager#17]
Hi,

wanted to try the latest version but:
- it is not published to npm
- the package.json main is incorrect (links to the lib folder which doesn't exist), so can't use directly from github
- The syntax is not compatible with Babel6

**Comment by juhaelee** [comment]
@souporserious could you cut a new release with the react 15 upgrade please? 🙏

**Comment by souporserious** [comment]
Should be fixed with this https://github.com/souporserious/react-motion-slider/commit/47f7c5a06e7abb198bc9e8975e2783b04af10413 sorry about that. @ju1ius if you want to use directly from Github use the dist files, if you use npm it will pull from the lib folder. Please let me know if it still isn't working.
